version: "3.1"
services:
  cassandra:
    image: cassandra:3
    container_name: cassandra
    volumes:
      - cassandra-data:/var/lib/cassandra
    ports:
      - "9042:9042"

# Add volumes definition to create volume mysql-data referenced above
volumes:
  cassandra-data:
    driver: "local"
    driver_opts:
      type: "none"
      o: "bind"
      device: "/app/kong/cassandra"    


