version: "3.3"
services:
  nginx:
    image: nginx:latest
    container_name: init-web-container
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www/html/build:/usr/share/nginx/html

