version: '3.1'
services:
  mongo:
   image: mongo
   container_name: mongo_db
   restart: always
   environment:
     MONGO_INITDB_ROOT_USERNAME: root
     MONGO_INITDB_ROOT_PASSWORD: 123456
   volumes:
     - mongo-data:/data/db
   ports:
     - 27017:27017
volumes:
 mongo-data:
  driver: "local"
  driver_opts:
    type: "none"
    o: "bind"
    device: "/app/mongo"
