version: '3.1'
services:
  db:
    image: postgres
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  postgres-data:
    driver: "local"
    driver_opts:
      type: "none"
      o: "bind"
      device: "/app/data"

