version: "3.3"
services:
  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./cert/etc/letsencrypt/live/qa.mxdai.co/fullchain.pem:/etc/letsencrypt/live/qa.mxdai.co/fullchain.pem
      - ./cert/etc/letsencrypt/live/qa.mxdai.co/privkey.pem:/etc/letsencrypt/live/qa.mxdai.co/privkey.pem
      - ./cert/etc/letsencrypt/live/stg.mxdai.co/fullchain.pem:/etc/letsencrypt/live/stg.mxdai.co/fullchain.pem
      - ./cert/etc/letsencrypt/live/stg.mxdai.co/privkey.pem:/etc/letsencrypt/live/stg.mxdai.co/privkey.pem
      - ./cert/etc/letsencrypt/live/stg-jp-dashboard.hottab.us/fullchain.pem:/etc/letsencrypt/live/stg-jp-dashboard.hottab.us/fullchain.pem
      - ./cert/etc/letsencrypt/live/stg-jp-dashboard.hottab.us/privkey.pem:/etc/letsencrypt/live/stg-jp-dashboard.hottab.us/privkey.pem
    networks:
      - hottab-net
networks:
  hottab-net:
    driver: bridge
